---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: nemo
spec:
  lookupPolicy:
    local: true
  tags:
  - name: 'dev'
      openshift.io/imported-from: nvcr.io/nvidia/nemo:dev
    scheduled: true
    from:
      kind: DockerImage
      name: nvcr.io/nvidia/nemo:dev
    referencePolicy:
      type: Local
  - name: latest
    from:
      kind: ImageStreamTag
      name: nemo:dev
    referencePolicy:
      type: Local
