hub:
  config:
    JupyterHub:
      admin_access: true
      authenticator_class: dummy
  podSecurityContext:
    fsGroup:
  containerSecurityContext:
    runAsGroup: 
    runAsUser:
  networkPolicy:
    enabled: false

proxy:
  chp:
    containerSecurityContext:
      runAsGroup: 
      runAsUser:
    networkPolicy:
      enabled: false
  service:
    type: ClusterIP

scheduling:
  userScheduler:
    enabled: false
  podPriority:
    enabled: false
  userPlaceholder:
    enabled: false

singleuser:
  profileList:
  - display_name: "Sample notebook"
    description: "Default image for JupyterHub"
    kubespawner_override:
      image: sample-notebook:latest
    default: true  
  - display_name: "Basic notebook server"
    description: "Just python3 and you"
    kubespawner_override:
      image: minimal-notebook:latest
  - display_name: "Data science notebook server"
    description: "Python (with lots of libraries), R, and Julia all running."
    kubespawner_override:
      image: datascience-notebook:latest
  cloudMetadata:
    blockWithIptables: false
  networkPolicy:
    enabled: false
  uid:
  fsGid:

prePuller:
  hook:
    enabled: false
  continuous:
    enabled: false

ingress:
  enabled: false

cull:
  enabled: true
  users: false # --cull-users
  adminUsers: true # --cull-admin-users
  removeNamedServers: false # --remove-named-servers
  timeout: 3600 # --timeout
  every: 600 # --cull-every
  concurrency: 10 # --concurrency
  maxAge: 0 # --max-age

debug:
  enabled: true

global:
  safeToShowValues: true