---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: datascience-notebook
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      annotations: null
      from:
        kind: DockerImage
        name: 'docker.io/jupyter/datascience-notebook:latest'
      importPolicy:
        scheduled: true
        importMode: Legacy
      referencePolicy:
        type: Local
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: minimal-notebook
  namespace: jupyterhub
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      annotations: null
      from:
        kind: DockerImage
        name: 'docker.io/jupyter/minimal-notebook:latest'
      importPolicy:
        scheduled: true
        importMode: Legacy
      referencePolicy:
        type: Local
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: sample-notebook
  namespace: jupyterhub
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      annotations: null
      from:
        kind: DockerImage
        name: 'docker.io/jupyterhub/k8s-singleuser-sample:2.0.0'
      importPolicy:
        scheduled: true
        importMode: Legacy
      referencePolicy:
        type: Local
